### PR TITLE
fix(mdf4): error maximum recursion exceeded

### PR DESCRIPTION
**Pull request by JulienGrv**
Fix issue #21

### CODE REVIEW

**Comment by JulienGrv** [comment]
That's right, I will edit this

**Comment by JulienGrv** [comment]
I can do a copy of ch_cntr like this:

```python
from copy import copy

[...]

index = copy(ch_cntr)
grp['channel_dependencies'].append(None)
ch_cntr, composition = self._read_channels(
    channel['component_addr'],
    grp,
    stream,
    dg_cntr,
    ch_cntr,
    True,
)
grp['channel_dependencies'][index] = composition
```

I could also user insert() instead of appending None, what do you think is most suitable?

**Comment by danielhrisca** [comment]
just a simple ``index = ch_cntr `` is enough.

**Comment by JulienGrv** [comment]
No, I tried and it does not work unfortunately.

**Comment by danielhrisca** [comment]
It should be ``index = ch_ntr - 1`` because _ch_cntr_ is incremented just before the _if_ statement.

**Comment by JulienGrv** [comment]
Oh! Alright! and insert?

**Comment by danielhrisca** [comment]
I think it's better to leave it like it is with appending.

**Comment by danielhrisca** [comment]
Thank you Julien for fixing this subtle bug.

**Pull request merged**
