### PR TITLE
Use tempfile.TemporaryDirectory() for tests.

### PR DESCRIPTION
**Pull request by kopytjuk**
Use `tempfile.TemporaryDirectory()` for the tests - cleaning up is easy integrated within the temp-dir object.

### CODE REVIEW

**Comment by kopytjuk** [comment]
@danielhrisca maybe interesting for the Py3 release ... just recognized that Py2 does not have a std-lib support for temporal directories.

**Comment by danielhrisca** [comment]
Please make a new PR on the Py3 branch. Thank you!

**Comment by danielhrisca** [comment]
@kopytjuk 
can adapt the Py3 code to use tempfile.TemporaryDirectory()?

**Comment by kopytjuk** [comment]
> @kopytjuk
> can you adapt the Py3 code to use tempfile.TemporaryDirectory()?

@danielhrisca yes, will create a MR in a few days

**Comment by danielhrisca** [comment]
great, thank you

**Pull request closed without merging**
