### PR TITLE
fix some incorrect type annotations

### PR DESCRIPTION
**Pull request by JulienGrv**

### CODE REVIEW

**Comment by danielhrisca** [comment]
thank you Julien!

**Comment by danielhrisca** [comment]
BTW if you use the Tabular window you should check out the development branch since I've switched to a new implementation

**Comment by danielhrisca** [comment]
@JulienGrv do you have further ideas for the 7.0.0 release?

**Comment by JulienGrv** [comment]
No I think it's good now, I've checked the type annotations multiple times now

**Comment by JulienGrv** [comment]
And I have no other breaking change in mind

**Pull request merged**
