### PR TITLE
Use cibuildwheel to build and test wheels

### PR DESCRIPTION
**Pull request by zariiii9003**
This is just a suggestion, feel free to close it.

It looks like a huge change, but i had to move `asammdf` into `src`. Otherwise pytest would try to test the repository code instead of the built and installed wheels. This would fail because there is no `cutil` binary in the repository. With the `asammdf` folder hidden in `src`, it works fine.
The git history of all the moved files  should remain untouched.

I see that you had the same issue and  just put `usedevelop = true` into the tox.ini file. But that is not really a solution for the problem, because it does not test the source distribution.

### CODE REVIEW

**Comment by danielhrisca** [comment]
Thanks for the PR @zariiii9003. I'm not experienced with all this CI stuff.

Can you have a look on why this tests are failing? I can't tell why it happens. 

https://github.com/danielhrisca/asammdf/actions/runs/3804656101/jobs/6472027912

**Comment by danielhrisca** [comment]
Never mind I think it was just some failed test

**Comment by zariiii9003** [comment]
Yes, two windows test are failing, but they are failing locally, too:

```
  =========================== short test summary info ===========================
  FAILED D:\a\asammdf\asammdf\test\test_mdf.py::TestMDF::test_cut - OSError: [Errno 22] Invalid argument: 'C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\tmpcgeuvxwa\\tmp0.mf4'
  FAILED D:\a\asammdf\asammdf\test\test_mdf.py::TestMDF::test_cut_demo - OSError: [Errno 22] Invalid argument: 'C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\tmpcgeuvxwa\\tmp1.mf4'
  ================== 2 failed, 52 passed, 1 warning in 14.83s ===================
```

**Comment by danielhrisca** [comment]
I've fixed the tests. Can you resolve the new conflicts?

**Comment by zariiii9003** [comment]
There's a sphinx warning `D:\a\asammdf\asammdf\.tox\doc\lib\site-packages\asammdf\blocks\mdf_v4.py:docstring of asammdf.blocks.mdf_v4.MDF4.get_invalidation_bits:1: WARNING: more than one target found for cross-reference 'Channel': asammdf.blocks.v2_v3_blocks.Channel, asammdf.blocks.v4_blocks.Channel`. Otherwise it should be fine now

**Comment by danielhrisca** [comment]
I think you should run black and isort again.

**Comment by danielhrisca** [comment]
Thank you Artur!

**Pull request merged**
