### PR TITLE
ignore parsing error of comment in mdf_v4._process_can_logging

### PR DESCRIPTION
**Pull request by JulienGrv**

### CODE REVIEW

**Comment by danielhrisca** [comment]
Thank you Julien!

**Comment by danielhrisca** [comment]
What recording application causes this problem?

**Comment by JulienGrv** [comment]
The comment was not of xml format but just a name

**Comment by JulienGrv** [comment]
@danielhrisca the name was something like: CAN2_XXX.CAN_DataFrame

**Pull request merged**
