### PR TITLE
Activate pyflakes rules in ruff

### PR DESCRIPTION
**Pull request by zariiii9003**
@danielhrisca  I added a few rules to "ignore", could you take a look at those and push fixes to this PR?

- "F821",  # undefined-name:  
  - 5 occurrences,  these are obvious bugs which must be fixed

- "F401",  # unused-import
  - 15 occurrences, ruff suggests to `consider importlib.util.find_spec to test for availability`

- "F841",  # unused-variable
  - 53 occurrences, these could just be removed, but maybe you left them for informational purposes. These could be fixed with a `_` prefix

### CODE REVIEW

**Comment by danielhrisca** [comment]
how can I run ruff to see the warnings?

**Comment by zariiii9003** [comment]
> how can I run ruff to see the warnings?

`ruff check ./src`

But you have to comment out the ignored rules in pyproject.toml to see the warnings.

**Comment by zariiii9003** [comment]
@danielhrisca Can you merge this? I'll fix the other stuff in a separate PR. This one contains no logic changes.

**Comment by danielhrisca** [comment]
Thanks

**Pull request merged**
