### PR TITLE
fix(mdf_v4): uint8 data type is converted to bool

### PR DESCRIPTION
**Pull request by JulienGrv**
I saw you convert data to bool when the bit_count is equal to 1. But still, in MDF Validator, the data type is 0 so this should be a uint IMHO.

### CODE REVIEW

**Comment by danielhrisca** [comment]
Hello Julien,

I think we should make this an option for the _configure_ method by taking into account the following:
* there is no dedicated data type for boolean 
* CANape and Inca treat single bit unsigned channels as logical channels (see also issue #53)
* there is added information to single bit channels that is lost if they are treated as uint8 channels (this happens with _cut_, _convert_, _filter_, _concatenate_ and _stack_ methods)
* everybody can choose how single bit unsigned values are treated (bool/uint8)

The best way would probably be to pass the new configuration option to _get_fmt_v3_, _get_fmt_v4_, _fmt_to_datatype_v3_ and _fmt_to_datatype_v4_
 

It is also necessary to implement the same behavior for mdf version 2 and 3 as well.

**Comment by danielhrisca** [comment]
It appears that CANape treats all unsigned channels with bit a bitcount less or equal to 4 as logical channels.

This is how CANape displays a 4bit unsigned channel:

image

and the same channel, with the bit count set to 5:

image

**Comment by JulienGrv** [comment]
Hi Daniel,

CANape treats the channel as a logical channel for the graphic view, but when you look at the property, it is still a uint, isn't it? I think the conversion to bool should be done for the plotting part, but not for the reading part.

> there is added information to single bit channels that is lost if they are treated as uint8 channels (this happens with cut, convert, filter, concatenate and stack methods)
What do you mean by that? What information will be lost?

**Comment by danielhrisca** [comment]
> What do you mean by that? What information will be lost?

I mean that if you see a 1-bit channel you can be sure it is a flag.

What I would like to have is a mechanism to preserve the bit count for unsigned channels with <=8 bits, and the option to return 1-bit channels as numpy bool if the user desires.

**Comment by JulienGrv** [comment]
The option sounds good to me, at least it makes it clear on the user side why that it is an intended behaviour

**Comment by danielhrisca** [comment]
Seeing that you have not made progress in this pull request I went ahead and made an implementation (https://github.com/danielhrisca/asammdf/commit/a4e53524dd457aab5a33d178aee54a560be5a0c0): 
* the default is now to return _uint8_ instead of _bool_
* the user can configure to get _bool_ instead of _uint8_
* the bit count is preserved in case of unsigned channels with bit count <=4

What do you think?

**Comment by JulienGrv** [comment]
It looks perfect! I will close this PR. I can't wait for the next release, this one will probably be my new favourite :)

**Pull request closed without merging**
