### PR TITLE
Fix for issue #741.

### PR DESCRIPTION
**Pull request by eblis**
Added progress information while sorting all the groups.
 - Added 102 extra steps in the load progress, 100 for sorting and 2 after sorting is completed.
 - When incrementing the progress updates during sorting we first compute a step, based on the total number of steps we have (100), the number of groups and the total items and then we increment each sorting by the step count.
 - If the previous step count (integer) is greater than the current step (integer) then we can update the progress. This avoids calling the callback function with floating values and avoids calling the callback function with the same current value of the progress bar - i.e. we only call when there's an update in progress.

### CODE REVIEW

**Comment by danielhrisca** [comment]
@eblis please resolve the merging conflict

**Comment by danielhrisca** [comment]
@eblis please try out the development branch code (you need to recompile the c extension code as well) for a big speed-up in the sorting

**Comment by eblis** [comment]
Sorting speed improvement sounds very good.
But still the progress stuff should help, no ? It will still report during the sorting steps, even though they might be a [lot] faster now.

**Comment by danielhrisca** [comment]
thank you!

**Comment by danielhrisca** [comment]
@eblis are you using a custom _callback function?

**Pull request merged**
