### PR TITLE
[Bugfix] do not edit groups if no processed can

### PR DESCRIPTION
**Pull request by JulienGrv**
Fix issue #139

### CODE REVIEW

**Comment by JulienGrv** [comment]
@danielhrisca can you do a release after? Thx Daniel!

**Comment by danielhrisca** [comment]
Do you have this warning?

https://github.com/danielhrisca/asammdf/blob/development/asammdf/blocks/mdf_v4.py#L616

**Comment by JulienGrv** [comment]
No because [this condition](https://github.com/danielhrisca/asammdf/blob/c97d0c87427f102c4b2cfb8a7af48682fb89d5c8/asammdf/blocks/mdf_v4.py#L555) if False

**Comment by danielhrisca** [comment]
I think line 619 to 649 should be removed

**Comment by JulienGrv** [comment]
More precisely, no but after that nothing is processed because can_msg ist False

**Comment by JulienGrv** [comment]
> 
> 
> I think line 619 to 649 should be removed

Perhaps, I'm not sure here

**Comment by JulienGrv** [comment]
How do you know [here ](https://github.com/danielhrisca/asammdf/blob/c97d0c87427f102c4b2cfb8a7af48682fb89d5c8/asammdf/blocks/mdf_v4.py#L537)that the correct attachment is the second one?

**Comment by danielhrisca** [comment]
I think this cause the problem. Can you check removing those lines fixes it?

**Comment by JulienGrv** [comment]
> 
> 
> I think this cause the problem. Can you check removing those lines fixes it?

I don't think so because this code is not executed. Line [537](https://github.com/danielhrisca/asammdf/blob/c97d0c87427f102c4b2cfb8a7af48682fb89d5c8/asammdf/blocks/mdf_v4.py#L537) is True

**Comment by danielhrisca** [comment]
See [here](https://github.com/danielhrisca/asammdf/blob/c97d0c87427f102c4b2cfb8a7af48682fb89d5c8/asammdf/blocks/mdf_v4.py#L4616) and [here](https://github.com/danielhrisca/asammdf/blob/c97d0c87427f102c4b2cfb8a7af48682fb89d5c8/asammdf/blocks/mdf_v4.py#L3491)

**Comment by danielhrisca** [comment]
Please also remove lines 619 to 649 as it makes no sense to create new groups with not added information compared to the original ones

**Comment by JulienGrv** [comment]
Ok line [537](https://github.com/danielhrisca/asammdf/blob/c97d0c87427f102c4b2cfb8a7af48682fb89d5c8/asammdf/blocks/mdf_v4.py#L537) is True but the file is not available in my computer. Maybe we should check for the file existence here?

**Comment by JulienGrv** [comment]
> 
> 
> Please also remove lines 619 to 649 as it makes no sense to create new groups with not added information compared to the original ones

Will do

**Comment by JulienGrv** [comment]
This is what I got when I print(attachment) after line [536](https://github.com/danielhrisca/asammdf/blob/c97d0c87427f102c4b2cfb8a7af48682fb89d5c8/asammdf/blocks/mdf_v4.py#L536):

```
(b'', WindowsPath('../../database/dbc/<name>.dbc'))
(b'', WindowsPath('../../database/dbc/<name>.dbc'))
(b'', WindowsPath('../../database/dbc/<name>.dbc'))
(b'', WindowsPath('../../database/dbc/<name>.dbc'))
(b'', WindowsPath('../../database/dbc/<name>.dbc'))
(b'', WindowsPath('../../database/dbc/<name>dbc'))
```

I just replaced file names with <name>

**Comment by danielhrisca** [comment]
Correct we should add ``and attachment[1].exists()`` at line 537

**Comment by JulienGrv** [comment]
> 
> 
> Correct we should add `and attachment[1].exists()` at line 537

Ok and what about the empty byte string? Because I saw you try to load it line [541](https://github.com/danielhrisca/asammdf/blob/c97d0c87427f102c4b2cfb8a7af48682fb89d5c8/asammdf/blocks/mdf_v4.py#L541)
We could also simply check that byte string is not empty, no?

**Comment by danielhrisca** [comment]
> Ok and what about the empty byte string? Because I saw you try to load it line [541](https://github.com/danielhrisca/asammdf/blob/c97d0c87427f102c4b2cfb8a7af48682fb89d5c8/asammdf/blocks/mdf_v4.py#L541)
> We could also simply check that byte string is not empty, no?

Even better like this

**Comment by JulienGrv** [comment]
I think we can also revert [this commit](https://github.com/danielhrisca/asammdf/commit/855867c6788f55cc12402f32c30b297ef63f83c4) afterward

**Comment by danielhrisca** [comment]
> I think we can also revert [this commit](https://github.com/danielhrisca/asammdf/commit/855867c6788f55cc12402f32c30b297ef63f83c4) afterward

Actually that one must remain: we can append signal extracted from the known CAN messages, and only remove the raw data group if all messages were found in the CAN database

**Comment by danielhrisca** [comment]
Thank you Julien!

**Comment by JulienGrv** [comment]
Thank you too! I'm glad I could learn a bit about CAN bus logging handling

**Comment by danielhrisca** [comment]
@JulienGrv 
I've made some changes in the development branch. Can you check if the new code still works correctly with your files?

**Comment by JulienGrv** [comment]
@danielhrisca sure! Not before next week though. Thanks for letting me know

**Comment by JulienGrv** [comment]
Hi Daniel,

Just a follow up about the new CAN bus logging handling. It works but it displays quite a few warning messages:

```console
asammdf - WARNING - Exception during attachment extraction: FileNotFoundError(2, 'No such file or directory')
asammdf - WARNING - Expected .dbc or .arxml file as CAN channel attachment but got "..\..\database\dbc\<filename>.dbc"
asammdf - WARNING - Exception during attachment extraction: FileNotFoundError(2, 'No such file or directory')
asammdf - WARNING - Expected .dbc or .arxml file as CAN channel attachment but got "..\..\database\dbc\<filename>.dbc"
asammdf - WARNING - Exception during attachment extraction: FileNotFoundError(2, 'No such file or directory')
asammdf - WARNING - Expected .dbc or .arxml file as CAN channel attachment but got "..\..\database\dbc\NI5\DADCA_A_UNCAN_NCR18Q2_180516.dbc"
asammdf - WARNING - Exception during attachment extraction: FileNotFoundError(2, 'No such file or directory')
asammdf - WARNING - Expected .dbc or .arxml file as CAN channel attachment but got "..\..\database\dbc\<filename>.dbc"
asammdf - WARNING - Exception during attachment extraction: FileNotFoundError(2, 'No such file or directory')
asammdf - WARNING - Expected .dbc or .arxml file as CAN channel attachment but got "..\..\database\dbc\<filename>.dbc"
asammdf - WARNING - Exception during attachment extraction: FileNotFoundError(2, 'No such file or directory')
asammdf - WARNING - Expected .dbc or .arxml file as CAN channel attachment but got "..\..\database\dbc\<filename>.dbc"
asammdf - WARNING - Exception during attachment extraction: FileNotFoundError(2, 'No such file or directory')
asammdf - WARNING - Expected .dbc or .arxml file as CAN channel attachment but got "..\..\database\dbc\<filename>.dbc"
asammdf - WARNING - Exception during attachment extraction: FileNotFoundError(2, 'No such file or directory')
asammdf - WARNING - Expected .dbc or .arxml file as CAN channel attachment but got "..\..\database\dbc\<filename>.dbc"
asammdf - WARNING - Exception during attachment extraction: FileNotFoundError(2, 'No such file or directory')
asammdf - WARNING - Expected .dbc or .arxml file as CAN channel attachment but got "..\..\database\dbc\<filename>.dbc"
asammdf - WARNING - Exception during attachment extraction: FileNotFoundError(2, 'No such file or directory')
asammdf - WARNING - Expected .dbc or .arxml file as CAN channel attachment but got "..\..\database\dbc\<filename>.dbc"
asammdf - WARNING - Exception during attachment extraction: FileNotFoundError(2, 'No such file or directory')
asammdf - WARNING - Expected .dbc or .arxml file as CAN channel attachment but got "..\..\database\dbc\<filename>.dbc"
asammdf - WARNING - Exception during attachment extraction: FileNotFoundError(2, 'No such file or directory')
asammdf - WARNING - Expected .dbc or .arxml file as CAN channel attachment but got "..\..\database\dbc\<filename>.dbc"
asammdf - WARNING - Exception during attachment extraction: FileNotFoundError(2, 'No such file or directory')
asammdf - WARNING - Expected .dbc or .arxml file as CAN channel attachment but got "..\..\database\dbc\<filename>.dbc"
asammdf - WARNING - Exception during attachment extraction: FileNotFoundError(2, 'No such file or directory')
asammdf - WARNING - Expected .dbc or .arxml file as CAN channel attachment but got "..\..\database\dbc\<filename>.dbc"
asammdf - WARNING - Exception during attachment extraction: FileNotFoundError(2, 'No such file or directory')
asammdf - WARNING - Expected .dbc or .arxml file as CAN channel attachment but got "..\..\database\dbc\<filename>.dbc"
asammdf - WARNING - Exception during attachment extraction: FileNotFoundError(2, 'No such file or directory')
asammdf - WARNING - Expected .dbc or .arxml file as CAN channel attachment but got "..\..\database\dbc\<filename>.dbc"
asammdf - WARNING - Exception during attachment extraction: FileNotFoundError(2, 'No such file or directory')
asammdf - WARNING - Expected .dbc or .arxml file as CAN channel attachment but got "..\..\database\dbc\<filename>.dbc"
asammdf - WARNING - Exception during attachment extraction: FileNotFoundError(2, 'No such file or directory')
asammdf - WARNING - Expected .dbc or .arxml file as CAN channel attachment but got "..\..\database\dbc\<filename>.dbc"
asammdf - WARNING - Exception during attachment extraction: FileNotFoundError(2, 'No such file or directory')
asammdf - WARNING - Expected .dbc or .arxml file as CAN channel attachment but got "..\..\database\dbc\<filename>.dbc"
[...]
```

But I guess it is the expected behaviour so I won't bother much

**Comment by danielhrisca** [comment]
Hello Julien,

please run again with the latest development branch. Is should warn that the attachment is not found

**Comment by JulienGrv** [comment]
You're as fast as a rocket :)

The new warning message:

```console
asammdf - WARNING - Exception during attachment extraction: FileNotFoundError(2, 'No such file or directory')
asammdf - WARNING - Attachment "..\..\database\dbc\<filename>.dbc" not found
asammdf - WARNING - Exception during attachment extraction: FileNotFoundError(2, 'No such file or directory')
asammdf - WARNING - Attachment "..\..\database\dbc\<filename>.dbc" not found
asammdf - WARNING - Exception during attachment extraction: FileNotFoundError(2, 'No such file or directory')
asammdf - WARNING - Attachment "..\..\database\dbc\<filename>.dbc" not found
[...]
```

**Pull request merged**
