### PR TITLE
Follow the abstract class design pattern

### PR DESCRIPTION
**Pull request by JulienGrv**
Hi @danielhrisca 

If I am correct, MDF_Common is an abstract class so I propose this refactoring for _filter_occurrences which better follows this design pattern

### CODE REVIEW

**Comment by danielhrisca** [comment]
What I had in mind with the class was to use it as a mixin and avoid code duplication

**Comment by JulienGrv** [comment]
Ok. I will let it as a Mixin but I prefer to make two _filter_occurrences implementations otherwise I have to do this `if self.version >= "4.0"`

**Comment by danielhrisca** [comment]
> Ok. I will let it as a Mixin but I prefer to make two _filter_occurrences implementations otherwise I have to do this `if self.version >= "4.00"`

ok, sounds good

**Comment by danielhrisca** [comment]
Thank you Julien!

**Pull request merged**
