### PR TITLE
Streamline continuous integration between remote and local

### PR DESCRIPTION
**Pull request by JulienGrv**
Hi @danielhrisca 

Thanks to tox, we can run tests locally just like it will be on the remote.
Currently, it runs unit tests against python version 3.7, 3.8, 3.9 and 3.10 on ubuntu, windows and macos. It does a style check with black and isort and generates the documentation.

Can you tell me what is missing so that we can completely drop appveyor and travis?

### CODE REVIEW

**Comment by danielhrisca** [comment]
The `appveyor` jobs that are run on the `master` branch generate the standalone executable s (using PyInstaller).

I think that the documentation is generated automatically by `read the docs`.

I think that `travis` could be disabled.

**Comment by JulienGrv** [comment]
There are 3 workflows since they are trigger on different events:

- continuous integration (main.yml): this one is triggered on any push, it runs all the tests on every platform / python version.
- coveralls: this one is only triggered for pushes and pull request on the master or development branch.
- build: triggered for push that contains a tag that follows semantic versioning (example: 3.4.5). It creates wheels for all platform / python version. It also create one executable for each platform.

Ok so I think that with this, we can drop appveyor. What do you think?

**Comment by danielhrisca** [comment]
This is some heavy lifting work that you did.

If the wheels and executables can be generated with the new workflow then we can drop appveyor

**Comment by JulienGrv** [comment]
Wheels and executables can be generated. You can actually test by yourself, if you checkout the branch and then create a tag like 3.6.7 and push it.

**Comment by JulienGrv** [comment]
Honestly I did this heavy lifting because I wanted to be able to locally reproduce the tests happening remotely and I thought it's a good exercise to learn github actions. Feel free to play with my branch and test if it does what you need

**Comment by JulienGrv** [comment]
Currently the branch does not remove appveyor so we can merge it as is and you cna start using github actions and when you feel confident enough you can drop appveyor yourself

**Comment by JulienGrv** [comment]
Also I just realized that appveyor is broken currently so this could save the day :)

**Comment by danielhrisca** [comment]
Very nice work Julien!

**Comment by danielhrisca** [comment]
I've pushed a tag but I can't find the exe builds. Is this only valid for the `master` branch?

**Comment by JulienGrv** [comment]
It should work for any branch

**Comment by JulienGrv** [comment]
Ah I see why, we have to adapt the pattern to support dev releases, look here

**Pull request merged**
