### PR TITLE
fix(blocks.v2_v3_blocks): ModuleNotFoundError: No module named 'pwd'

### PR DESCRIPTION
**Pull request by JulienGrv**

### CODE REVIEW

**Comment by danielhrisca** [comment]
`getuser`  seems to work on Windows. On which OS did you have problems?

**Comment by JulienGrv** [comment]
on Windows, the environment variables are all empty in my case, so it tries to fallback on using pwd but pwd is no available on Windows so it raises ModuleNotFoundError

**Comment by JulienGrv** [comment]
Have a look here https://github.com/JulienGrv/asammdf/runs/4118929891?check_suite_focus=true#step:5:355

**Comment by danielhrisca** [comment]
I had no idea this does not work. Thanks!

**Pull request merged**
