### PR TITLE
add scrambling of attachments in mdf.scramble

### PR DESCRIPTION
**Pull request by JulienGrv**

### CODE REVIEW

**Comment by danielhrisca** [comment]
Hello Julien,

I think we should also write 0x00 bytes for the embedded attachment data, via a new argument to the function that default to True.

**Comment by JulienGrv** [comment]
Hi Daniel,

Makes sense, how should we name the option? skip_attachments=False ? or maybe just attachments=True ?

**Comment by danielhrisca** [comment]
I think that _skip_attachments=False_ is clear

**Comment by JulienGrv** [comment]
Ok, do you have a measurement sample for me with embedded attachment?

**Comment by danielhrisca** [comment]
```python
from asammdf import MDF

m = MDF()

m.attach(b'sample attachment', 'sample.bin', 'this is a demo attachment')

m.save('attachment.mf4')
```

**Comment by danielhrisca** [comment]
Thank you Julien!

**Comment by JulienGrv** [comment]
You're welcome. Can you do a release? Thanks

**Pull request merged**
